version: '2'
services:
  musixmatch-api-service:
    build: .
    volumes:
      - ${PWD}/output:/output
    environment:
      - DEFAULT_WORD=car
      - OUTPUT_FILE_NAME=musixmatch-script-results.csv